// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCommentLike struct {
	CommentID string `json:"commentID"`
	UserJwt   string `json:"userJWT"`
}

type CommentLike struct {
	CommentID string   `json:"commentID"`
	Comment   *Comment `json:"comment"`
	UserID    string   `json:"userID"`
	User      *User    `json:"user"`
}
