// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID          string    `json:"id"`
	Post        *Post     `json:"post"`
	PostID      string    `json:"postID"`
	Commenter   *User     `json:"commenter"`
	CommenterID string    `json:"commenterID"`
	Content     string    `json:"content"`
	CreatedAt   time.Time `json:"createdAt"`
}

type NewComment struct {
	UserJwt string `json:"userJWT"`
	PostID  string `json:"postID"`
	Content string `json:"content"`
}
