// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPostLike struct {
	PostID  string `json:"postID"`
	UserJwt string `json:"userJWT"`
}

type PostLike struct {
	PostID string `json:"postID"`
	Post   *Post  `json:"post"`
	UserID string `json:"userID"`
	User   *User  `json:"user"`
}
