// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewReplyLike struct {
	ReplyID string `json:"replyID"`
	UserJwt string `json:"userJWT"`
}

type ReplyLike struct {
	ReplyID string `json:"replyID"`
	Reply   *Reply `json:"reply"`
	UserID  string `json:"userID"`
	User    *User  `json:"user"`
}
