// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewReply struct {
	UserJwt   string `json:"userJWT"`
	CommentID string `json:"commentID"`
	Content   string `json:"content"`
}

type Reply struct {
	ID        string    `json:"id"`
	Comment   *Comment  `json:"comment"`
	CommentID string    `json:"commentID"`
	Replier   *User     `json:"replier"`
	ReplierID string    `json:"replierID"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
}
