// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BlockNotification struct {
	UserID string `json:"userID"`
	ToID   string `json:"toID"`
}

type Relation struct {
	UserJwt string `json:"userJWT"`
	ToID    string `json:"toID"`
}

type RemoveSuggestion struct {
	UserID string `json:"userID"`
	ToID   string `json:"toID"`
}
